import { Button } from '../views/button/button.js';
import { ContentList } from '../views/split-view/content-list.js';
import { Image } from '../views/image/image.js';
import { Outline } from '../views/outline/outline.js';
import { ScrollView } from '../views/scroll-view/scroll-view.js';
import { SideBar } from '../views/split-view/sidebar.js';
import { Slider } from '../views/slider/slider.js';
import SplitView from '../views/split-view/split-view.js';
import { TableCell } from '../views/table/table-cell.js';
import { Text } from '../views/text/text.js';
import { View } from '../views/view/view.js';
import { Window } from '../views/window/window.js';
import { WebView } from '../views/webview/webview.js';
import { registerGlobalDocument } from './environment.js';
import { Checkbox } from '../views/checkbox/checkbox.js';
import { ComboBox } from '../views/combobox/combobox.js';
import { Progress } from '../views/progress/progress.js';
import { Toolbar } from '../views/toolbar/toolbar.js';
import { ToolbarItem } from '../views/toolbar/toolbar-item.js';
import { ToolbarToggleSidebar } from '../views/toolbar/toolbar-toggle-sidebar.js';
import { ToolbarSidebarTrackingSeparator } from '../views/toolbar/toolbar-sidebar-tracking-separator.js';
import { ToolbarFlexibleSpace } from '../views/toolbar/toolbar-flexible-space.js';
import { ToolbarGroup } from '../views/toolbar/toolbar-group.js';
import { RadioButton } from '../views/radiobutton/radiobutton.js';
import { FileOpenButton } from '../views/fileopenbutton/fileopenbutton.js';
import { ColorOpenButton } from '../views/coloropenbutton/coloropenbutton.js';
import { FileSaveButton } from '../views/filesavebutton/filesavebutton.js';
import { TextField } from '../views/text-field/text-field.js';
import { Menu } from '../views/menu/menu.js';
import { MenuItem } from '../views/menu/menu-item.js';
import { MenuSeparator } from '../views/menu/menu-separator.js';
import { MenuSectionHeader } from '../views/menu/menu-section-header.js';
import { StatusBar } from '../views/status-bar/status-bar.js';
import { Popover } from '../views/popover/popover.js';
import { Switch } from '../views/switch/switch.js';
import { DatePicker } from '../views/date-picker/date-picker.js';
Button.register();
Checkbox.register();
ColorOpenButton.register();
ComboBox.register();
ContentList.register();
FileOpenButton.register();
FileSaveButton.register();
Image.register();
Outline.register();
Progress.register();
RadioButton.register();
ScrollView.register();
SplitView.register();
SideBar.register();
Slider.register();
TableCell.register();
Text.register();
Toolbar.register();
ToolbarItem.register();
ToolbarToggleSidebar.register();
ToolbarSidebarTrackingSeparator.register();
ToolbarFlexibleSpace.register();
ToolbarGroup.register();
WebView.register();
Window.register();
View.register();
TextField.register();
Menu.register();
MenuItem.register();
MenuSeparator.register();
MenuSectionHeader.register();
StatusBar.register();
Popover.register();
Switch.register();
DatePicker.register();
registerGlobalDocument();
